sudo: false
language: cpp
python:
  - "2.7"

install:
  - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  - tar -xvf emsdk-portable.tar.gz
  - cd emsdk-portable
  - ./emsdk update
  - ./emsdk install latest
  - ./emsdk activate latest
#  - source ./emsdk_env.sh

script:
  - python tests/runner.py test_hello_world

notifications:
  email: false
