sudo: false
language: cpp
python:
  - "2.7"

install:
  - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  - tar -xvf emsdk-portable.tar.gz
  - ./emsdk update
  - ./emsdk install latest
  - ./emsdk activate latest

script:
  - ./check.py

notifications:
  email: false
